version: '3'
services:
    app:
        image: "0548964d2bcf/project1"
        build: .
        ports:
            - "8080:8080"
    nginx:
        image: "nginx:alpine"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/www/media
        depends_on: 
            - app
        ports:
            - "80:80"